### ISSUE TITLE
Standardise UTF-8 for primitive string data type

### ISSUE THREAD

**Issue by MathiasVDA** [SchweizerischeBundesbahnen/rcm-dx#12]
In https://github.com/SchweizerischeBundesbahnen/rcm-dx/blob/main/RCM-DX-Specification_EN.md#primitive-data-types

Can we standardise the use of UTF-8 for string types?

**Comment by Jean-FredericBonjour** [comment]
Hi Mathias,
Great to see you on rcm-dx. Welcome!
UTF-8 is supported by rcm-dx. Other encoding should be supported too.
If you encounter any problems with string format, let me know and we will help you.

**Comment by pumelo** [comment]
According to HDF5 spec. only ASCII and UTF-8 is supported. Metadata stored with the string type makes it clear which one is used.

https://docs.hdfgroup.org/hdf5/develop/_h5_tpublic_8h.html#a03755b8370672668ddc7063add28e71a
