### ISSUE TITLE
Please define "platform structure"

### ISSUE THREAD

**Issue by MathiasVDA** [SchweizerischeBundesbahnen/rcm-dx#14]
In https://github.com/SchweizerischeBundesbahnen/rcm-dx/blob/main/RCM-DX-Specification_EN.md#attributes-1 please define the term "platform structure"

**Comment by Jean-FredericBonjour** [comment]
Hi Mathias
Here an example
![image](https://user-images.githubusercontent.com/106162857/231146788-942baa30-73b8-46ed-bcbf-8747cc6cf529.png)

The StructureVersion is [vehicleName]_[systemName]_[fileContentVersion] = DFZ00_TGMS_v003
