### ISSUE TITLE
Unclear definition in clearance attribute

### ISSUE THREAD

**Issue by MathiasVDA** [SchweizerischeBundesbahnen/rcm-dx#15]
In https://github.com/SchweizerischeBundesbahnen/rcm-dx/blob/main/RCM-DX-Specification_EN.md#clearance-group under the attribute "clearance", it seems that the status PENDING and UNRELEASED both mean the same thing?

Is there a value that would indicate that the file is corrupt or the measurement should be disregarded entirely?

**Comment by Jean-FredericBonjour** [comment]
Hi Mathias
We use PENDING on our workflow to interrupt the processing and review files manually. But most of the time RELEASED or UNRELEASED is set on the vehicle by the measurement crew. Finally only RELEASED files are indexed on our database. UNRELEASED files are deleted after a certain amount of time. PENDING files stay in workflow until they have been manually reviewed and set on RELEASED or UNRELEASED.
