### ISSUE TITLE
Clearance of individual or parts of the measurement data

### ISSUE THREAD

**Issue by MathiasVDA** [SchweizerischeBundesbahnen/rcm-dx#16]
Is there a possibility to set the status on a part of the measurement? In https://github.com/SchweizerischeBundesbahnen/rcm-dx/blob/main/RCM-DX-Specification_EN.md#clearance-group it seems to be possible to set the clearance for the complete file but is there also the possibility to set this status for a part of the file?

**Comment by Jean-FredericBonjour** [comment]
Hi Mathias
in rcm-dx you have the possibility to flag a part of a file or even only a datasource/channel. Please you for this purpose AVAILABILITY
![image](https://user-images.githubusercontent.com/106162857/231153134-2ba317f1-5e31-47ca-92d0-2b5cc1c5a4e0.png)
We will probably merge AVAILABILITY and CONSISTENCY. We will keep only AVAILABILITY

**Comment by VBP8501** [comment]
Perfect, thanks!
