### ISSUE TITLE
Please add structure image of session configuration group

### ISSUE THREAD

**Issue by MathiasVDA** [SchweizerischeBundesbahnen/rcm-dx#17]
Here: https://github.com/SchweizerischeBundesbahnen/rcm-dx/blob/main/RCM-DX-Specification_EN.md#session-configuration-group

To be consistent with the rest of the document. Please create an image and add it to the document.

**Comment by Jean-FredericBonjour** [comment]
Hi Mathias

Configuration is between Session Group and Topology Group:
![image](https://user-images.githubusercontent.com/106162857/231154471-d017763b-3b2a-44f4-bc8f-c50ac8226b9a.png)
