### ISSUE TITLE
Please define section

### ISSUE THREAD

**Issue by VBP8501** [SchweizerischeBundesbahnen/rcm-dx#18]
Please define the term "section" as meant in the sections group: 
https://github.com/SchweizerischeBundesbahnen/rcm-dx/blob/main/RCM-DX-Specification_EN.md#sections-group

**Comment by Jean-FredericBonjour** [comment]
Hi Matthias
By SBB we have most of the time a section per file or session. A Section should be created each time the orientation of travel (vehicle direction: forward/backward) change. So you have the possibility to generate a file/session for long period of time and each section represent an other run (vehicle orientation).
