### ISSUE TITLE
Please rename 'direction' to 'orientation'

### ISSUE THREAD

**Issue by MathiasVDA** [SchweizerischeBundesbahnen/rcm-dx#19]
Here: https://github.com/SchweizerischeBundesbahnen/rcm-dx/blob/main/RCM-DX-Specification_EN.md#sections-group

The attribute 'direction' is defined but the 'orientation' of the vehicle is meant.

**Comment by Jean-FredericBonjour** [comment]
Hi Mathias
Good point. In rcm-dx there are both. direction and kilometrage. The direction define if the vehicle is moving forward or backward. kilometrage define the orientation of the track. In following example you see there is one direction for the whole section but each track has its own kilometrage value (0:ASCENDING / 1: DESCENDING)

![image](https://user-images.githubusercontent.com/106162857/231157048-58768188-e10c-4464-add2-e2ca257bb149.png)

**Comment by VBP8501** [comment]
Also see EN13848-1 for naming

**Comment by MathiasVDA** [comment]
We decided to clarify the definition in the text but not change label to avoid issues with backwards compatibility
