### ISSUE TITLE
Inconsistency in contributing documentation

### ISSUE THREAD

**Issue by VBP8501** [SchweizerischeBundesbahnen/rcm-dx#21]
The contributing documentation state to use labels for any issues that are created by the community. But by default, it is not possible for the community to do this due to a lack of permissions.

**Comment by Jean-FredericBonjour** [comment]
Thx Mathias. We have change the contribution documentation and remove the use of labels.
https://github.com/SchweizerischeBundesbahnen/rcm-dx/blob/main/CONTRIBUTING.md
